## Пример задачи свертки

Задаем изображение и фильтр.

In [1]:
import numpy as np

image = np.array([[1, 2, 0, 0, 3],
              	  [0, 1, 2, 3, 1],
              	  [0, 0, 1, 2, 3],
              	  [3, 2, 1, 2, 0],
              	  [1, 0, 3, 1, 2]])

filter = np.array([[1, 0, 1],
               	  [0, 1, 0],
               	  [1, 0, 1]])

Применяем свертку между изображением и фильтром:


In [12]:
feature_map = np.zeros((3, 3))
for i in range(3):
	for j in range(3): feature_map[i][j] = np.sum(image[i:i+3, j:j+3] * filter)

print(feature_map)


[[ 3.  6. 10.]
 [ 6.  9.  6.]
 [ 7.  4. 11.]]
